apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REF
      type: string
    - name: APP_NAME
      type: string
    - name: IMAGE_NAME
      type: string
    - name: BASE_URL
      type: string
  workspaces:
    - name: pipeline-workspace
  tasks:
    # --- 1. clone -----------------------------------------------------------
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    # --- 2. lint ------------------------------------------------------------
    - name: pylint
      taskRef:
        name: pylint
      runAfter:            # ensure code is present before linting
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # --- 3. unit tests ------------------------------------------------------
    - name: run-tests
      taskRef:
        name: pytest-env
      runAfter:
        - pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # --- 4. build & push image ---------------------------------------------
    - name: build-image
      taskRef:
        name: build-and-push
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)

    # --- 5. deploy all k8s manifests ----------------------------------------
    - name: deploy-manifests
      runAfter:
        - build-image
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: manifest-dir
          value: "k8s"

    # --- 6. BDD tests against deployment -----------------------------------
    - name: run-bdd
      taskRef:
        name: behave-test
      runAfter:
        - deploy-manifests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: BASE_URL
          value: $(params.BASE_URL)
