apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REF
      type: string
    - name: APP_NAME
      type: string
    - name: IMAGE_NAME
      type: string
    - name: BASE_URL
      type: string
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: pylint
      taskRef:
        name: pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: run-tests
      taskRef:
        name: pytest-env
      runAfter:
        - pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace
    
    - name: build-image
      taskRef:
        name: build-and-push
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
    
    - name: deploy
      taskRef:
        name: deploy-image
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image-name
          value: $(params.IMAGE_NAME)

    - name: run-bdd
      taskRef:
        name: behave-test
      runAfter:
        - deploy
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: BASE_URL
          value: $(params.BASE_URL)


