apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pylint
spec:
  workspaces:
    - name: source
  steps:
    - name: run-pylint
      image: quay.io/rofrano/python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        pip install pylint
        pylint service/